### ISSUE TITLE
Implement `logs` Action

### ISSUE THREAD

**Issue by jaypipes** [gdt-dev/kube#20]
Allow logs for a Pod to be fetched and analyzed by GDT asserters. Pods should be looked up by name prefix to avoid the test author needing to know the exact Pod name. For example, the test author should be able to specify `logs: kube-scheduler` and GDT should look for any Pods that start with the string "kube-scheduler" and grab the logs from those Pods.

Something like this would work:

```yaml
tests:
 - name: check api-server loaded custom resource
   kube.logs: kube-apiserver
   assert:
     contains: Loaded MyCustomResource
```
