### ISSUE TITLE
Implement scheduling/placement asserters

### ISSUE THREAD

**Issue by jaypipes** [gdt-dev/kube#7]
I'd like an easy way of expressing scheduling assertions for pods in Kubernetes.

I'm thinking a declarative assertion block that looks like this:

```yaml
tests:
 - kube.get: deployments/nginx
   assert:
     placement:
       spread:
        - kubernetes.io/hostname
        - topology.kubernetes.io/zone
```

would instruct GDT/kube to do the following:

* fetch the `nginx` Deployment information, including the bound hosts for all Pods involved in the Deployment.
* fetch all the Node information
* assert that the Pods in the `nginx` Deployment are evenly spread across Nodes with the same `topology.kubernetes.io/zone`  and `kubernetes.io/hostname` label

```yaml
tests:
 - kube.get: deployments/nginx
   assert:
     placement:
       spread: topology.kubernetes.io/zone
       pack: kubernetes.io/hostname      
```

would instruct GDT/kube to do the following:

* fetch the `nginx` Deployment information, including the bound hosts for all Pods involved in the Deployment.
* fetch all the Node information
* assert that the Pods in the `nginx` Deployment are evenly spread across Nodes with the same `topology.kubernetes.io/zone` label
* assert that the Pods in the `nginx` Deployment that are placed within a `topology.kubernetes.io/zone` are bin-packed onto the same `kubernetes.io/hostname`
